@startuml MCP 工作流

autoactivate on

Actor User as U
participant "MCP HOST" as H
participant "MCP Client" as C
participant "MCP Server" as S
participant "大模型" as M

U -> H: 用户在聊天界面发送问答类信息
H -> C: 会把信息发送给 client 处理
C --> C: 初始化 client 实例
C -> M: 发送用户问答以及当前 host 装载的 mcp 工作列表
M -> M: 推理内容
M --> C: 返回需要推理内容、使用的工具列表
alt 调用工具列表存在
  loop 遍历工具列表
  C -> S: 建立服务连接
    alt 建立连接成功
      C -> S: 模型处理好的参数
      S -> S: 接受参数
      S -> S: 函数执行
      S --> C: 处理好的信息流
      C -> M: 发送 Server 处理好的信息
      M -> M: 二次处理 \n (.etc 这里我有个疑惑点就是 Server 返回的信息模型能根据前面的上下文二次处理？）
      M --> C: 模型二次处理结果
    else 建立连接失败
      C --> H: 流程失败信息
    end
  end
else 
  C --> H: 返回模型处理好的文本信息(数据流)
end


@enduml