@startuml 频控
start

:应用实例, 获取元数据;
if(元数据获取成功?) then(yes)
  :排除已经过期的配置;
  :剩下的根据时间戳降序排序得到最新配置;
else(no)    
  :设置默认频控配置（无负反馈）;
  note right
    频控 72小时 1次
  end note
endif

:入口触发曝光 / 点击;

note right
概念理解
1. x 小时内只弹出一次：x 小时指的是第一次触发的时间 ～ 当前
2. 用户拒绝了 x 次后 y 小时不弹出：y 小时指的是拒绝了 x + 1 次触发时间 ～ 当前

关键词解读
1. 入口 storage：快应用持久存储的数据库
2. 入口 storage 负反馈触发次数：执行拒绝加桌这个操作的次数
3. 入口 storage 频控触发次数：执行曝光 或 点击这个操作的次数
4. 入口 storage 频控上一次触发时间戳：在一个周期内执行曝光 或 点击这个操作的第一次时间戳
5. 入口 storage 负反馈最后触发时间戳：在一个周期内执行拒绝加桌这个操作的最后一次时间戳
end note

partition 前置 storage 数据刷新 {
  if(快应用 storage 存在当前入口的策略数据) then(no)
    :入口 storage 频控触发次数初始化为 0
    入口 storage 负反馈触发次数为 0
    入口 storage 频控上一次触发时间为当前时间戳
    入口 storage 负反馈最后触发时间为当前时间戳;
  else
      :计算入口上一次触发时间时间和当前时间戳的间隔;
      if(时间间隔 > 频控配置的时间间隔) then(yes)
        :入口 storage 频控触发次数重置为 0
        更新入口 storage 频控上一次触发时间戳为当前时间戳;
      endif
      if(负反馈配置存在 且 时间间隔 > 负反馈配置的时间间隔) then(yes)
        :入口 storage 负反馈触发次数重置为 0;
      elseif(负反馈配置不存在) then(yes)
        :入口 storage 负反馈触发次数重置为 0;
        note right
          针对前边配置了负反馈
          但是新的规则覆盖后无负反馈的场景
          是否需要对负反馈次数做重置？
        end note
      endif
  endif
}

:入口 storage 频控触发次数 + 1;

if(入口负反馈触发次数(拒绝加桌次数) <= 负反馈配置次数) then(yes)
  if(入口频控触发次数 == 0) then(yes)
    :更新入口 storage 频控上一次触发时间戳为当前时间戳;
  endif
  if(入口频控触发次数 < 频控配置次数) then(yes)
    :弹出加桌弹框;
    if(点击拒绝加桌?（点击关闭图标不纳入这个范围）) then(yes)
      :入口 storage 负反馈触发次数 + 1
      更新入口 storage 负反馈最后触发时间戳为当前时间戳;
    endif
  else(no)
    :不弹出加桌弹框;
  endif
else(no)
  :不弹出加桌弹框;
endif

end
@enduml