name: 个人博客部署

on:
  push:
    branches:
      - docs

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone code
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Run build script
        run: |
          npm run docs:build

      - name: Deploy to Aliyun
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .vuepress/dist
